[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.branch-deploy]
  [context.branch-deploy.environment]
    YARN_VERSION = "1.22.19"
    NODE_VERSION="18.16.0"


[context.deploy-preview]
  [context.deploy-preview.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION="18.16.0"
